### ISSUE TITLE
Layouts mais acessíveis

### ISSUE THREAD

**Issue by Marlysson** [lojaskd/frontend-challenge#2]
Teria a possibilidade de deixar os layouts nos formatos .png ? Para agilizar a visualização do teste.

**Comment by nandomoreirame** [comment]
Mas os layouts estão todos em .psd @Marlysson

Baixe o pojeto e veja dentro do diretório [/layouts](https://github.com/lojaskd/frontend-challenge/tree/master/layouts)

**Comment by nandomoreirame** [comment]
Adicionei os PNG's :+1:
